services:
  antenna-tracker-main:
    build: .
    image: antennatracker:latest
    container_name: antenna-tracker-main
    volumes:
      - ./config.yaml:/app/config.yaml:rw
    #restart: unless-stopped
    network_mode: host
    stop_signal: SIGKILL
    privileged: true
    stdin_open: true
    tty: true

  antenna-tracker-mavproxy:
    build: .
    image: antennatracker:latest
    container_name: antenna-tracker-mavproxy
    volumes:
      - ./mavsdk.sh:/app/mavsdk.sh:ro
    #restart: unless-stopped
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    stop_signal: SIGKILL
    entrypoint: ["bash", "mavsdk.sh"]
